AspNetCoreFundamentals_Coursework/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AspNetCoreFundamentals_Coursework.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AspNetCoreFundamentals_Coursework/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AspNetCoreFundamentals_Coursework.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AspNetCoreFundamentals_Coursework/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AspNetCoreFundamentals_Coursework.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AspNetCoreFundamentals_Coursework/Pages/Restaurants/ClientRestaurants.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreFundamentals_Coursework.Pages.Restaurants
{
    public class ClientRestaurantsModel : PageModel
    {
    }
}

AspNetCoreFundamentals_Coursework/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreFundamentals_Coursework.Pages.Restaurants
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData data;

        public Restaurant Restaurant { get; set; }
        public DeleteModel(IRestaurantData data)
        {
            this.data = data;
        }
        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = data.GetById(restaurantId);
            if(Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
        public IActionResult OnPost(int restaurantId)
        {
            var restaurant = data.Delete(restaurantId);
            data.Commit();
            if(restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{restaurant.Name} has been deleted.";
            return RedirectToPage("./List");
        }
    }
}

AspNetCoreFundamentals_Coursework/Pages/Restaurants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreFundamentals_Coursework.Pages.Restaurants
{
    public class DetailModel : PageModel
    {
        public Restaurant Restaurant { get; set; }

        [TempData]
        public string Message { get; set; }

        private readonly IRestaurantData _data;
        public DetailModel(IRestaurantData data)
        {
            _data = data;
        }
        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = _data.GetById(restaurantId);
            if(Restaurant is null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

AspNetCoreFundamentals_Coursework/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AspNetCoreFundamentals_Coursework.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData data;
        private readonly IHtmlHelper helper;

        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public EditModel(IRestaurantData data, IHtmlHelper helper)
        {
            this.data = data;
            this.helper = helper;
        }

        
        public IActionResult OnGet(int? restaurantId)
        {
            Cuisines = helper.GetEnumSelectList<CuisineType>();
            if (restaurantId.HasValue)
            {
                Restaurant = data.GetById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();
            }
            if(Restaurant is null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                Cuisines = helper.GetEnumSelectList<CuisineType>();
                return Page();
            }
            if (Restaurant.Id > 0)
            {
                data.Update(Restaurant);
            }
            else
            {
                data.Create(Restaurant);
            }
            data.Commit();
            TempData["Message"] = "Restaurant saved!";
            return RedirectToPage("./Detail/", new { restaurantId = Restaurant.Id,  });
        }
    }
}

AspNetCoreFundamentals_Coursework/Pages/Restaurants/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace AspNetCoreFundamentals_Coursework.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        private readonly IRestaurantData _data;
        private readonly IConfiguration config;

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public IEnumerable<Restaurant> Restaurants { get; set; }
        public ListModel(IConfiguration configuration, IRestaurantData data)
        {
            config = configuration;
            _data = data;
        }
        public void OnGet()
        {
            Restaurants = _data.GetByName(SearchTerm);
        }
    }
}

AspNetCoreFundamentals_Coursework/ViewComponents/RestaurantCountViewComponent.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreFundamentals_Coursework.ViewComponents
{
    public class RestaurantCountViewComponent
        : ViewComponent
    {
        private readonly IRestaurantData data;

        public RestaurantCountViewComponent(IRestaurantData data)
        {
            this.data = data;
        }
        public IViewComponentResult Invoke()
        {
            var count = data.Count();
            return View(count);
        }
    }
}

AspNetCoreFundamentals_Coursework/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetCoreFundamentals_Coursework/Pages/Restaurants/ClientRestaurants.cshtml
@page
@model AspNetCoreFundamentals_Coursework.Pages.Restaurants.ClientRestaurantsModel
@{
    ViewData["Title"] = "ClientRestaurants";
}

<h1>Client Restaurants</h1>

<table class="table" id="restaurants">

</table>

@section Scripts {

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.js"></script>

    <script>
        const cuisines = ['None',
            'Italian',
            'Mexican',
            'Chinese',
            'Pizza'];
        $(function () {
            $.ajax("/api/restaurants/", { method: "get" })
                .then((response) => {
                    $("#restaurants").dataTable({
                        data: response,
                        columns: [
                            { "data": "name" },
                            { "data": "location" },
                            { "data": "cuisine", "render": function (data) { return cuisines[data]; }}
                        ],
                    });
                });
        });
    </script>
}

AspNetCoreFundamentals_Coursework/Pages/Restaurants/Delete.cshtml
@page "{restaurantId}"
@model AspNetCoreFundamentals_Coursework.Pages.Restaurants.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Restaurant</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurant.Name (@Model.Restaurant.Location)? 
</div>
<form method="post">
    <button type="submit" class="btn btn-danger">Yes</button>
    <a asp-page="List" class="btn btn-info">Cancel</a>
</form>

AspNetCoreFundamentals_Coursework/Pages/Restaurants/Detail.cshtml
@page "{restaurantId:int}"
@model AspNetCoreFundamentals_Coursework.Pages.Restaurants.DetailModel
@{
    ViewData["Title"] = "Detail";
}

@if (Model.Message != null)
{
    <div class="alert alert-info">@Model.Message</div>
}

<h1>@Model.Restaurant.Name</h1>

<div>
    Id: @Model.Restaurant.Id
</div>
<div>
    Location: @Model.Restaurant.Location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>
<a asp-page="./List" class="btn btn-success">Back To List</a>

AspNetCoreFundamentals_Coursework/Pages/Restaurants/Edit.cshtml
@page "{restaurantId:int?}"
@model AspNetCoreFundamentals_Coursework.Pages.Restaurants.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>@(Model.Restaurant.Id > 0 ? "Editing" : "Adding") @(Model.Restaurant.Name != null ? Model.Restaurant.Name : "Restaurant")</h1>

<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div class="form-group">
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Location"></label>
        <input asp-for="Restaurant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Location"></span>

    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine" class="form-control" asp-items="Model.Cuisines">
        </select>
        <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>

    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AspNetCoreFundamentals_Coursework/Pages/Restaurants/List.cshtml
@page
@model AspNetCoreFundamentals_Coursework.Pages.Restaurants.ListModel
@{
    ViewData["Title"] = "List";
}

<h1 class="text-info">Restaurants</h1>

<form method="get">
    <div class="container row p-0">
        <div class="col-9">
            <input type="search" class="form-control" asp-for="SearchTerm"/>
        </div>
        <div class="col-3">
            <button class="btn btn-info form-control text-white m-0">Search</button>
        </div>
    </div>
</form>
@foreach(var item in Model.Restaurants)
{
    <partial name="_Summary" model="item" />
}
@*<table class="table table-striped border">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
            <th>Cuisine Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var restaurant in Model.Restaurants)
        {
        <tr>
            <td>@restaurant.Name</td>
            <td>@restaurant.Location</td>
            <td>@restaurant.Cuisine</td>
            <td>
                <a asp-page="./Detail" asp-route-restaurantId="@restaurant.Id" class="btn btn-info">Details</a>
                <a asp-page="./Edit" asp-route-restaurantId="@restaurant.Id" class="btn btn-success">Edit</a>
                <a asp-page="./Delete" asp-route-restaurantId="@restaurant.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>*@

<a asp-page="./Edit" class="btn btn-primary">+ Add New Restaurant</a>

AspNetCoreFundamentals_Coursework/Pages/Restaurants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1 class="text-danger">Restaurant Data Wasn't Found.</h1>
<a asp-page="./List" class="btn btn-info">See List of Restaurants</a>

AspNetCoreFundamentals_Coursework/Pages/Restaurants/_Summary.cshtml
@using Core
@model Restaurant

<div class="card m-1">
    <div class="card-header">
        <h3>@Model.Name</h3>
    </div>
    <div class="card-body">
        <div>Location: @Model.Location</div>
        <div>Cuisine: @Model.Cuisine</div>
    </div>
    <div class="card-footer">
        <a asp-page="./Detail" asp-route-restaurantId="@Model.Id" class="btn btn-info">Details</a>
        <a asp-page="./Edit" asp-route-restaurantId="@Model.Id" class="btn btn-success">Edit</a>
        <a asp-page="./Delete" asp-route-restaurantId="@Model.Id" class="btn btn-danger">Delete</a>
    </div>
</div>

AspNetCoreFundamentals_Coursework/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="card card-text bg-light">
    There are @Model restaurants in the database. <a asp-page="/Restaurants/List" >View All</a> 
</div>

AspNetCoreFundamentals_Coursework/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreFundamentals_Coursework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AspNetCoreFundamentals_Coursework</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <vc:restaurant-count></vc:restaurant-count>
        <div class="container">
            &copy; 2020 - AspNetCoreFundamentals_Coursework - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
        @RenderSection("footer", required: false)
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>